spring:
  boot:
    admin:
      client:
        url: https://mlog.dayukeji.xin/
        password: Dayu!234
        username: dayukeji
  # >>> 数据库相关 <<< *
  datasource:
    name: wx-official-test
    # 用户名
    username: d1641
    # 密码
    password: D@yu2OIqi
    url: jdbc:mysql://localhost:3306/wx-official-test?useSSL=false&serverTimezone=GMT%2b8&useUnicode=true&characterEncoding=utf-8
  redis:
    host: localhost
    password: Dayu1234
    port: 6379
    database: 1
  # ** 监控端口 ** #
management:
  server:
    port: 10009
    endpoint:
      logfile:
        enabled: true
      loggers:
        enabled: true
# >>> 项目相关 <<< *
server:
  # 项目端口
  port: 9999
env-config:
  ip: 192.168.2.151  #开发服内网ip
  notify-template: SMS_146804689
  file-upload-path: /var/www/static/p9999/
  default-image: https://tst.dayukeji.xin/static/p9999/default.jpg
  root-url: https://tst.dayukeji.xin/static/p9999/
  secret-path: /usr/local/lib/wxmch/cert-dykj.p12
  # ** 自定义 ** #
  version: 1.3
  # ** 必填 ** #
  project: mptest
  # ** 需要做session的 ** #
  intercept-list:
    /**
  user-appid: wx33e5389d1a2cde19
  user-secret: fa132a5549b1ca9dc92081e752d12340
  access-Url: tst.dayukeji.xin/mptest/api/auth/login
  wallet-ip: 60.205.186.191
third-service:
  tencent:
    wechat-pay:
      mch-id: 1509794011
      secret: apSP6c674e04cde71M8lF966c01e876a
      notify-url: https://tst.dayukeji.xin/p19015/api/wechatEcho
      refund-url: https://test.dayukeji.xin/p19015/api/common/wechatEcho
      refund:
        header:
          https-secret-path: /usr/local/lib/wxmch/cert-dykj.p12
    wechat-mini:
      appid: wx33e5389d1a2cde19
      secret: fa132a5549b1ca9dc92081e752d12340
